In [1]:
import cv2
import numpy as np
img = cv2.imread("Image_01.bmp")

In [2]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, binary_img = cv2.threshold(img, 110, 255, cv2.THRESH_BINARY)

In [3]:
row,col = img.shape


last_label = 20

pixel_array = []

index=0

In [4]:
for i in range(row):
    for j in range(col):
        if (binary_img[i,j]>200):
            
            if(binary_img[i,j-1]!=0 and binary_img[i,j-1]!=255):
                binary_img[i,j]=binary_img[i,j-1]
            elif(binary_img[i-1,j]!=0 and binary_img[i-1,j]!=255):
                binary_img[i,j] = binary_img[i-1,j]
            elif(binary_img[i-1,j+1]!=0 and binary_img[i-1,j+1]!=255):
                binary_img[i,j]= binary_img[i-1,j+1]
            elif(binary_img[i-1,j-1]==0):
                binary_img[i,j] = last_label
                last_label = last_label+1

In [5]:
for i in range(row):
    for j in range(col):
        
        if (img[i,j]>0):
            if(binary_img[i,j-1]!= 0):
                binary_img = np.where(binary_img==binary_img[i,j], binary_img[i,j-1],binary_img)
            if(binary_img[i-1,j]!=0):
                binary_img = np.where(binary_img==binary_img[i,j], binary_img[i-1,j],binary_img)
            if( (j+1)<col):
                if(binary_img[i-1,j+1]!=0):
                    binary_img =      np.where(binary_img==binary_img[i,j], binary_img[i-1,j+1],binary_img)
            if(i+1<row and j-1>0):
                if(binary_img[i+1,j-1]!=0):
                   binary_img =   np.where(binary_img==binary_img[i,j], binary_img[i+1,j-1],binary_img)

In [6]:
for i in range(row):
    for j in range(col):
        if (binary_img[i,j] != 0):
            if (binary_img[i,j] not in pixel_array):
                pixel_array.append(binary_img[i,j])
            else:
                continue

print(pixel_array)

[52, 64, 92, 99, 128, 135, 160, 163]


In [12]:
colored_img = cv2.cvtColor(binary_img, cv2.COLOR_GRAY2BGR)


for i in pixel_array:
    color = np.random.randint(100, 255, size=3) 
    print(color) 
    colored_img[binary_img == i] = color
    
cv2.imshow("image",binary_img)
cv2.imshow("rgb",colored_img)
print(img)
cv2.waitKey(0)

[245 107 105]
[165 156 228]
[209 190 146]
[250 131 230]
[137 202 165]
[234 176 170]
[244 103 221]
[155 241 197]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


-1